#!/bin/bash

# tasks/deploy
#   Deploy the site to the appropriate location.
#
#   Assumes that the `reclaim` host is setup appropriately in .ssh/config

# Settings.  These should probably exist somewhere else.
SITE=public_html/Courses/CSC151/Reference/
REMOTE=rebelsky.cs.grinnell.edu

# Feedback
echo $SITE

# Remake necessary stuff
make summaries

# Rebuild!
bundle exec jekyll build

rsync -rtz _site/ $REMOTE:$SITE
